import { ArrowRight, ChevronRight, Clock3, Leaf, Quote, ShieldCheck, Star, TreePine } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../features/auth/auth-provider';
import { useAddCartItem } from '../features/cart/hooks';
import { useShop, useShops } from '../features/shops/hooks';
import { formatRupees } from '../lib/utils';
import type { MenuItem } from '../types/api';
import { DashboardCafeteriaCard, type DashboardCafeteria } from '../components/dashboard-cafeteria-card';
import { DashboardFoodCard } from '../components/dashboard-food-card';

const image = (id: string, width = 1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=86`;
const categories = [['All', 'all', '◈'], ['North Indian', 'north-indian', '🥘'], ['South Indian', 'south-indian', '🍲'], ['Chinese', 'chinese', '🍜'], ['Snacks', 'snacks', '🍟'], ['Beverages', 'beverages', '🥤'], ['Healthy', 'healthy', '🥗'], ['Desserts', 'desserts', '🍰']] as const;
const fallbackCafeterias: DashboardCafeteria[] = [
  { name: 'Bite Box', slug: 'bite-box', imageUrl: image('photo-1552566626-52f8b828add9'), isOpen: true, rating: '4.6', reviews: '320', cuisine: 'North Indian · Chinese', hours: '8:00 AM – 9:00 PM', distance: '2 mins away', live: false },
  { name: 'The Food Hub', slug: 'the-food-hub', imageUrl: image('photo-1517248135467-4c7edcad34c4'), isOpen: true, rating: '4.5', reviews: '280', cuisine: 'South Indian · Snacks', hours: '8:00 AM – 8:00 PM', distance: '3 mins away', live: false },
  { name: 'Campus Cravings', slug: 'campus-cravings', imageUrl: image('photo-1515003197210-e0cd71810b5f'), isOpen: true, rating: '4.4', reviews: '190', cuisine: 'Chinese · Beverages', hours: '9:00 AM – 9:00 PM', distance: '5 mins away', live: false },
  { name: 'Healthy Bites', slug: 'healthy-bites', imageUrl: image('photo-1498837167922-ddd27525d352'), isOpen: false, rating: '4.3', reviews: '150', cuisine: 'Healthy · Salads', hours: '10:00 AM – 7:00 PM', distance: '7 mins away', live: false },
];
const fallbackDishes: MenuItem[] = [
  { id: 'demo-paneer', shopId: 'demo', categoryId: 'demo', categoryName: 'North Indian', categorySlug: 'north-indian', name: 'Paneer Butter Masala', description: 'Creamy tomato gravy with soft paneer.', pricePaise: 8000, imageUrl: image('photo-1601050690597-df0568f70950'), preparationTime: 15, isAvailable: true, isVegetarian: true, isSpicy: false, calories: 480, variants: [], addons: [] },
  { id: 'demo-biryani', shopId: 'demo', categoryId: 'demo', categoryName: 'Indian', categorySlug: 'indian', name: 'Veg Biryani', description: 'Aromatic rice with seasonal vegetables.', pricePaise: 7000, imageUrl: image('photo-1589302168068-964664d93dc0'), preparationTime: 18, isAvailable: true, isVegetarian: true, isSpicy: false, calories: 510, variants: [], addons: [] },
  { id: 'demo-roll', shopId: 'demo', categoryId: 'demo', categoryName: 'Snacks', categorySlug: 'snacks', name: 'Chicken Roll', description: 'A warm wrap packed with bold flavor.', pricePaise: 6000, imageUrl: image('photo-1628294895950-9805252327bc'), preparationTime: 12, isAvailable: true, isVegetarian: false, isSpicy: false, calories: 420, variants: [], addons: [] },
  { id: 'demo-fries', shopId: 'demo', categoryId: 'demo', categoryName: 'Snacks', categorySlug: 'snacks', name: 'French Fries', description: 'Crisp, golden, and perfectly salted.', pricePaise: 5000, imageUrl: image('photo-1573080496219-bb080dd4f877'), preparationTime: 8, isAvailable: true, isVegetarian: true, isSpicy: false, calories: 330, variants: [], addons: [] },
  { id: 'demo-coffee', shopId: 'demo', categoryId: 'demo', categoryName: 'Beverages', categorySlug: 'beverages', name: 'Cold Coffee', description: 'Smooth, chilled coffee for study breaks.', pricePaise: 5000, imageUrl: image('photo-1461023058943-07fcbe16d735'), preparationTime: 6, isAvailable: true, isVegetarian: true, isSpicy: false, calories: 210, variants: [], addons: [] },
];
function Heading({ title, subtitle, href = '/shops' }: { title: string; subtitle?: string; href?: string }) { return <div className="dashboard-section-header"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><Link className="dashboard-view-all" to={href}>View All <ChevronRight size={14} /></Link></div>; }
export function DashboardHomePage() {
  const { user } = useAuth(); const shops = useShops({ limit: 4, sort: 'popular' }); const featured = useShop(shops.data?.items[0]?.slug ?? ''); const add = useAddCartItem(); const firstName = user?.fullName?.split(' ')[0] ?? 'Vicky';
  const live = shops.data?.items.map((shop) => ({ name: shop.name, slug: shop.slug, imageUrl: shop.bannerUrl ?? image('photo-1552566626-52f8b828add9'), isOpen: shop.isOpen, rating: shop.rating.toFixed(1), reviews: String(shop.totalReviews), cuisine: shop.location, hours: '8:00 AM – 9:00 PM', distance: `${Math.max(2, shop.estimatedPreparationTime - 10)} mins away`, live: true })) ?? [];
  const cafes = live.length ? [...live, ...fallbackCafeterias].slice(0, 4) : fallbackCafeterias; const menu = featured.data?.menu.filter((item) => item.isAvailable).slice(0, 5) ?? []; const dishes = menu.length >= 3 ? menu : fallbackDishes;
  const addItem = (item: MenuItem) => { if (!user) { window.location.href = '/login'; return; } if (!item.id.startsWith('demo-')) void add.mutateAsync({ menuItemId: item.id, quantity: 1 }); };
  return <div className="dashboard-page">
    <section className="dashboard-hero-grid"><article className="dashboard-hero-card"><div className="dashboard-hero-copy"><p className="dashboard-eyebrow"><span>✦</span> GOOD FOOD, BETTER DAYS</p><h1>Fuel Your<br />Campus Life</h1><p>Delicious meals from your favorite cafeterias,<br className="dashboard-desktop-break" /> all in one place.</p><Link className="dashboard-hero-button" to="/shops">Order Now <ArrowRight size={16} /></Link></div><img className="dashboard-hero-image" src={image('photo-1547592180-85f173990554', 1200)} alt="Colorful fresh meal bowl" /><p className="dashboard-hero-scribble">Same<br />Campus<br />More Flavor <span>♡ ↘</span></p><div className="dashboard-hero-dots" aria-hidden="true"><span className="is-active" /><span /><span /><span /></div></article><article className="dashboard-healthy-card"><span className="dashboard-leaf-icon"><Leaf size={25} /></span><span className="dashboard-floating-leaf">⌁</span><h2>Fresh<br />Healthy<br />Delicious</h2><p>Meals made for<br />a better you.</p><span className="dashboard-leaf-mark">⌁</span></article></section>
    <section className="dashboard-category-section"><div className="dashboard-category-header"><h2>What are you craving?</h2><Link className="dashboard-view-all" to="/shops">View All <ChevronRight size={14} /></Link></div><div className="dashboard-category-rail">{categories.map(([label, slug, icon], index) => <Link className="dashboard-category-item" key={slug} to={slug === 'all' ? '/shops' : `/shops?category=${slug}`}><span className={index === 0 ? 'is-active' : ''}>{icon}</span><strong>{label}</strong></Link>)}</div></section>
    <section className="dashboard-section"><Heading title="Popular Cafeterias Near You" subtitle="Explore top-rated food outlets across your campus." /><div className="dashboard-cafe-grid">{cafes.map((cafe) => <DashboardCafeteriaCard cafe={cafe} key={cafe.slug} />)}</div></section>
    <section className="dashboard-section dashboard-dishes-section"><Heading title="Popular Dishes" subtitle="Most ordered and loved by students." /><div className="dashboard-food-grid">{dishes.map((item) => <DashboardFoodCard item={item} onAdd={() => addItem(item)} key={item.id} />)}</div></section>
    <section className="dashboard-promos"><article className="dashboard-promo dashboard-promo-dark"><div><h2>Student Special</h2><p>Get 20% off<br />on your first order!</p><Link to="/shops">Use Code: UNIEATS20</Link></div><img src={image('photo-1568901346375-23c9450c58cd', 650)} alt="Burger and fries" /><span>Good<br />Food.<br />Good Mood! ♡</span></article><article className="dashboard-promo dashboard-promo-light"><div><h2>Healthy Choices<br />Happier You</h2><p>Explore salads, protein meals<br />and more.</p><Link to="/shops?category=healthy">Explore Healthy Menu</Link></div><img src={image('photo-1512621776951-a57141f2eefd', 650)} alt="Healthy salad bowl" /><span>Eat<br />Smart.<br />Stay Active! ↙</span></article></section>
    <section className="dashboard-lower-grid"><article className="dashboard-lower-card"><div className="dashboard-lower-heading"><h2>Your Recent Orders</h2><Link to="/orders">View All</Link></div><div className="dashboard-order-list">{[[1, 'Veg Biryani', 'The Food Hub', 'Picked Up'], [2, 'Chicken Roll', 'Bite Box', 'Completed'], [4, 'Cold Coffee', 'Campus Cravings', 'Completed']].map(([index, name, cafe, status]) => <div className="dashboard-order-row" key={name}><img src={fallbackDishes[Number(index)].imageUrl ?? ''} alt="" /><div><strong>{name}</strong><span>{cafe}</span><small>12 Sept 2025, 1:20 PM</small></div><em>{status}</em></div>)}</div></article><article className="dashboard-lower-card"><div className="dashboard-lower-heading"><h2>Offers for You</h2><Link to="/notifications">View All</Link></div><div className="dashboard-offer-list"><div className="dashboard-offer-card dashboard-offer-yellow"><div><strong>FLAT 20% OFF</strong><span>On your first order</span><b>UNIEATS20</b></div><img src={fallbackDishes[0].imageUrl ?? ''} alt="" /></div><div className="dashboard-offer-card dashboard-offer-peach"><div><strong>Rs. 50 Cashback</strong><span>On orders above ₹200</span><b>EAT50</b></div><img src={fallbackDishes[3].imageUrl ?? ''} alt="" /></div></div></article><article className="dashboard-lower-card dashboard-impact-card"><div className="dashboard-lower-heading"><h2>Your Campus Impact</h2></div><div className="dashboard-impact-grid"><div><span><ShieldCheck size={18} /></span><strong>12<small>Orders Placed</small></strong></div><div><span><Leaf size={18} /></span><strong>5.0<small>CO₂ Saved (Using local food)</small></strong></div><div><span><TreePine size={18} /></span><strong>5.0 kg<small>CO₂ Saved</small></strong></div></div><div className="dashboard-impact-quote"><Quote size={17} /> “Good food fuels great minds!” <Leaf size={18} /></div></article></section>
    <div className="dashboard-assurance"><span><ShieldCheck size={15} /> Secure payments</span><span><Clock3 size={15} /> Quick pickup from campus favorites</span><span><Star size={15} fill="currentColor" /> Loved by students</span></div><span className="sr-only">Welcome, {firstName}. Prices start at {formatRupees(dishes[0]?.pricePaise ?? 0)}.</span>
  </div>;
}
