import { ArrowDownRight, ArrowRight, Check, Clock3, Leaf, MapPin, Search, ShieldCheck, Smartphone, Star } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { FoodCard } from '../components/food-card';
import { ShopCard } from '../components/shop-card';
import { EmptyState } from '../components/ui/empty-state';
import { LoadingSkeleton } from '../components/ui/loading-skeleton';
import { useAuth } from '../features/auth/auth-provider';
import { useAddCartItem } from '../features/cart/hooks';
import { useShop, useShops } from '../features/shops/hooks';
import { getApiError } from '../lib/errors';
import { unsplashImage } from '../lib/image-url';

const image = unsplashImage;
const categories = [['All', 'all', '◈'], ['Breakfast', 'breakfast', '🍳'], ['North Indian', 'north-indian', '🥘'], ['South Indian', 'south-indian', '🥙'], ['Chinese', 'chinese', '🍜'], ['Snacks', 'snacks', '🍟'], ['Beverages', 'beverages', '🥤'], ['Healthy', 'healthy', '🥗'], ['Desserts', 'desserts', '🍰']] as const;
const testimonials = [['Verified student stories', 'Reviews will appear here when the campus review module launches.', 'Coming Soon'], ['Fresh feedback, soon', 'We are keeping this space ready for real, verified student voices.', 'Coming Soon'], ['Built around your break', 'Order history and feedback will make every campus meal better.', 'Coming Soon']] as const;

function CategoryRail() {
  return <section className="category-wrap" aria-label="Browse food categories"><div className="section-shell"><div className="category-rail">{categories.map(([label, slug, icon], index) => <Link key={slug} className="category-item" to={slug === 'all' ? '/shops' : `/shops?category=${slug}`}><span className={`category-icon ${index === 0 ? 'active' : ''}`} aria-hidden="true">{icon}</span><span>{label}</span></Link>)}</div></div></section>;
}

export function HomePage() {
  const shops = useShops({ limit: 3, sort: 'popular' });
  const featuredSlug = shops.data?.items[0]?.slug ?? '';
  const featured = useShop(featuredSlug);
  const { user } = useAuth();
  const add = useAddCartItem();
  const navigate = useNavigate();
  const [notice, setNotice] = useState('');
  const shopItems = shops.data?.items ?? [];
  const menuItems = featured.data?.menu.filter((item) => item.isAvailable).slice(0, 4) ?? [];
  const shopCount = shops.data?.pagination.total ?? shopItems.length;
  const featuredRating = featured.data?.shop.rating.toFixed(1) ?? '—';
  const handleAdd = async (menuItemId: string, itemName: string) => {
    if (!user) { navigate('/login'); return; }
    setNotice('');
    try { await add.mutateAsync({ menuItemId, quantity: 1 }); setNotice(`${itemName} added to your cart.`); }
    catch (error) { setNotice(getApiError(error, 'We could not add that item. Please try again.')); }
  };

  return <div className="home-page">
    <section className="home-hero" aria-labelledby="hero-title"><span className="hero-orb orb-one" aria-hidden="true" /><span className="hero-orb orb-two" aria-hidden="true" /><div className="section-shell hero-grid"><div className="hero-copy"><p className="eyebrow">✦ Your campus food hub</p><h1 id="hero-title"><span>Good Food</span><strong>Brighter Days</strong><span>On Campus</span></h1><p className="hero-description">Order from your favorite campus cafés, explore delicious menus, enjoy easy pickup or delivery, and make every meal on campus special.</p><div className="hero-actions"><Link className="button-primary" to="/shops">Order Now <ArrowRight size={16} /></Link><Link className="button-secondary" to="/shops">Explore Menu</Link></div><div className="hero-stats" aria-label="UniEats highlights"><div className="hero-stat"><MapPin size={20} className="text-basil" /><span><strong>{shopCount || '—'}</strong><small>Approved cafeterias</small></span></div><div className="hero-stat"><Leaf size={20} className="text-ember" /><span><strong>Fresh</strong><small>Campus meals</small></span></div><div className="hero-stat"><Star size={20} className="text-ember" fill="currentColor" /><span><strong>{featuredRating}</strong><small>Featured rating</small></span></div></div><form className="hero-search-wrap hero-search" onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get('query')?.toString().trim() ?? ''; navigate(value ? `/shops?search=${encodeURIComponent(value)}` : '/shops'); }}><Search size={16} className="text-muted" /><input name="query" aria-label="Search food on campus" placeholder="Search for food, cafeterias..." /><button className="hero-search-submit" type="submit" aria-label="Search campus food"><ArrowRight size={16} /></button></form></div><div className="hero-visual" aria-label="Fresh campus meal"><div className="hero-photo"><img src={image('photo-1547592180-85f173990554', 1200)} alt="Colorful fresh noodle bowl" /></div><p className="hero-scribble">Same Campus<br />More Flavor <span>↘</span></p><div className="fresh-card"><span>✓</span><div><strong>Freshly Made</strong><small>for You</small></div></div><div className="hero-note"><strong>Fueling</strong><br />Students<br />Everyday ♡</div><div className="hero-arrows" aria-hidden="true"><button type="button"><ArrowRight size={15} className="rotate-180" /></button><button type="button"><ArrowRight size={15} /></button></div></div></div></section>
    <CategoryRail />
    <section className="home-section" aria-labelledby="favorites-title"><div className="section-shell popular-layout"><div className="section-copy"><p className="eyebrow">🔥 Popular this week</p><h2 id="favorites-title"><span>Student</span><strong>Favorites</strong></h2><p>Most loved dishes across campus cafeterias. Find something delicious for your next break.</p><Link className="section-link" to="/shops">View Full Menu <ArrowRight size={14} /></Link></div><div>{notice && <p className="notice" role="status">{notice}</p>}{featured.isLoading ? <div className="popular-grid">{[1, 2, 3, 4].map((item) => <LoadingSkeleton key={item} className="h-64" />)}</div> : menuItems.length ? <div className="popular-grid">{menuItems.map((item) => <FoodCard key={item.id} item={item} disabled={add.isPending} onAdd={() => void handleAdd(item.id, item.name)} />)}</div> : <EmptyState title="Menus are being prepared" description="Approved campus menu items will appear here as soon as they are available." />}</div></div></section>
    <section className="home-section cafeteria-panel" aria-labelledby="cafeterias-title"><div className="section-shell cafeteria-layout"><div className="section-copy"><p className="eyebrow">✦ Our cafeterias</p><h2 id="cafeterias-title"><span>Explore</span><br /><strong>Campus Cafés</strong></h2><p>Different flavors. Same campus. Find your nearest cafeteria and explore its special menu.</p><Link className="button-secondary" to="/shops">View All Cafeterias <ArrowRight size={15} /></Link></div><div className="campus-grid">{shops.isLoading ? [1, 2, 3].map((item) => <LoadingSkeleton key={item} className="h-80" />) : shopItems.length ? shopItems.map((shop) => <ShopCard key={shop.id} shop={shop} />) : <EmptyState title="No approved cafeterias yet" description="Cafeteria partners will appear here after approval." />}</div></div></section>
    <section className="home-section how-section" id="how-it-works" aria-labelledby="how-title"><div className="section-shell text-center"><p className="eyebrow">✦ How it works</p><h2 id="how-title" className="section-heading">Get Your Food in 3 Simple Steps</h2><div className="steps-grid"><article className="step-item"><div className="step-top"><span className="step-number">1</span><span className="step-icon">⌕</span></div><h3>Browse</h3><p>Explore menus from different campus cafeterias.</p></article><article className="step-item"><div className="step-top"><span className="step-number">2</span><span className="step-icon"><Smartphone size={20} /></span></div><h3>Order</h3><p>Add your favorite items to the cart and place your order.</p></article><article className="step-item"><div className="step-top"><span className="step-number">3</span><span className="step-icon"><Check size={20} /></span></div><h3>Pickup / Enjoy</h3><p>Pick up your food and enjoy your meal while it is fresh.</p></article></div></div></section>
    <section className="section-shell home-section" aria-labelledby="app-title"><div className="app-promo"><div className="phone-stack" aria-hidden="true"><div className="phone phone-back"><span className="phone-notch" /><div className="phone-screen dark"><p>Track Your<br />Order</p><div className="track-line"><span>✓</span>Order placed</div><div className="track-line"><span>✓</span>Preparing</div><div className="track-line"><span>✓</span>Ready for pickup</div></div></div><div className="phone phone-front"><span className="phone-notch" /><div className="phone-screen"><p>Good Morning,<br />Student! ✨</p><div className="phone-search">⌕ Search for food, cafeterias...</div><img src={image('photo-1601050690597-df0568f70950', 500)} alt="" /><small>Paneer Butter Masala</small></div></div></div><div className="app-copy"><p className="eyebrow">✦ On the go</p><h2 id="app-title">Your Campus Cafeteria<br /><strong>Now in Your Pocket</strong></h2><p>Order, track, and enjoy — anytime, anywhere. The UniEats mobile experience is being prepared for a future release.</p><p className="coming-label">Mobile app · Coming Soon</p><div className="store-buttons"><span className="store-button"><span className="store-icon">●</span><span><small>Coming soon on the</small>App Store</span></span><span className="store-button"><span className="store-icon">▶</span><span><small>Coming soon on</small>Google Play</span></span></div><div className="app-perks"><span><Check size={14} /> Fast ordering</span><span><ShieldCheck size={14} /> Secure account</span><span><Clock3 size={14} /> Pickup tracking</span></div></div></div></section>
    <section className="home-section testimonials-section" aria-labelledby="stories-title"><div className="section-shell"><div className="text-center"><p className="eyebrow">✦ What students say</p><h2 id="stories-title" className="section-heading">Loved by Thousands</h2><p className="mt-2 text-sm text-muted">Verified student reviews · Coming Soon</p></div><div className="testimonial-grid">{testimonials.map(([title, description, status]) => <article className="testimonial-card" key={title}><p>{description}</p><div className="testimonial-footer"><span className="testimonial-avatar" aria-hidden="true">✦</span><span><strong>{title}</strong><small>{status}</small></span><span className="stars" aria-label="Reviews coming soon">—</span></div></article>)}</div></div></section>
    <section className="section-shell home-section" id="contact"><div className="offer-banner"><div><p className="eyebrow text-[#d7f3df]">✦ Special offers · Coming Soon</p><h2>Good Food. Better Together.</h2><p>Promotions and student rewards will arrive in a future release. For now, discover today’s menus and pay cash when you pick up.</p><Link className="button-light" to="/shops">Explore Menu <ArrowRight size={15} /></Link></div><div className="offer-art"><img src={image('photo-1568901346375-23c9450c58cd', 650)} alt="Burger and fries" /><span><strong>Offers</strong><br />coming<br />soon</span><ArrowDownRight className="absolute bottom-4 left-8 text-white/70" size={30} /></div></div></section>
    <section className="section-shell pb-16"><div className="section-banner"><p className="eyebrow"><ShieldCheck size={13} className="inline" /> Built for campus breaks</p><p><span>Cash on pickup</span><span>•</span><span>Order history</span><span>•</span><span>Approved cafeterias only</span></p></div></section>
  </div>;
}
