import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import {
  ArrowRight, Bell, Check, ChevronDown, ChevronRight, CircleUserRound, Clock3, Coffee, Compass,
  Heart, Leaf, ListOrdered, LogOut, MapPin, Menu as MenuIcon, Minus, Navigation, Plus, Search,
  Share2, ShoppingBag, Star, TicketPercent, Utensils, WalletCards, X,
} from 'lucide-react';
import { Link, NavLink, useParams } from 'react-router-dom';
import { BrandMark } from '../components/brand-mark';
import { Footer } from '../components/footer';
import { useAuth } from '../features/auth/auth-provider';
import { useAddCartItem, useCart } from '../features/cart/hooks';
import { clearCart, removeCartItem, updateCartItem } from '../api/cart';
import { useShop } from '../features/shops/hooks';
import { getApiError } from '../lib/errors';
import { cn, formatRupees } from '../lib/utils';
import type { MenuItem, Shop } from '../types/api';
import { ErrorState } from '../components/ui/error-state';
import { LoadingSkeleton } from '../components/ui/loading-skeleton';

type ShowcaseItem = {
  id: string;
  apiItemId?: string;
  name: string;
  category: string;
  description: string;
  pricePaise: number;
  rating: number;
  reviews: number;
  image: string;
  isVeg: boolean;
  isSpicy?: boolean;
  badge?: 'Bestseller' | 'Popular';
};
type CartLine = Pick<ShowcaseItem, 'id' | 'name' | 'pricePaise' | 'image' | 'apiItemId'> & { quantity: number };
type TabId = 'menu' | 'about' | 'reviews' | 'photos' | 'location';
type DietFilter = 'all' | 'veg' | 'nonveg';

const HERO_IMAGE = 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=88';
const FOOD_IMAGES = {
  paneer: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=88',
  biryani: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=88',
  roll: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=88',
  coffee: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=88',
  chole: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=900&q=88',
  paratha: 'https://images.unsplash.com/photo-1626500155537-93690c24099e?auto=format&fit=crop&w=900&q=88',
  rajma: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=88',
  dal: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=900&q=88',
  noodles: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=88',
  chilliPaneer: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=900&q=88',
  manchurian: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=900&q=88',
  friedRice: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=88',
};
const SHOWCASE_MENU: ShowcaseItem[] = [
  { id: 'paneer-butter-masala', name: 'Paneer Butter Masala', category: 'Recommended', description: 'Creamy tomato gravy with soft paneer and warm spices.', pricePaise: 8000, rating: 4.8, reviews: 120, image: FOOD_IMAGES.paneer, isVeg: true, badge: 'Bestseller' },
  { id: 'veg-biryani', name: 'Veg Biryani', category: 'Recommended', description: 'Fragrant basmati rice cooked with garden-fresh veggies.', pricePaise: 7000, rating: 4.7, reviews: 98, image: FOOD_IMAGES.biryani, isVeg: true },
  { id: 'chicken-roll', name: 'Chicken Roll', category: 'Recommended', description: 'Grilled chicken wrapped with fresh greens and mint.', pricePaise: 6000, rating: 4.6, reviews: 150, image: FOOD_IMAGES.roll, isVeg: false, isSpicy: true, badge: 'Popular' },
  { id: 'cold-coffee', name: 'Cold Coffee', category: 'Recommended', description: 'Chilled coffee with a smooth, creamy finish.', pricePaise: 5000, rating: 4.6, reviews: 90, image: FOOD_IMAGES.coffee, isVeg: true },
  { id: 'chole-bhature', name: 'Chole Bhature', category: 'North Indian', description: 'Classic north Indian dish with spicy chickpea curry.', pricePaise: 7000, rating: 4.5, reviews: 80, image: FOOD_IMAGES.chole, isVeg: true, isSpicy: true },
  { id: 'aloo-paratha', name: 'Aloo Paratha', category: 'North Indian', description: 'Stuffed paratha with yogurt and house pickle.', pricePaise: 5000, rating: 4.4, reviews: 60, image: FOOD_IMAGES.paratha, isVeg: true },
  { id: 'rajma-chawal', name: 'Rajma Chawal', category: 'North Indian', description: 'Homestyle rajma with steamed rice and fresh coriander.', pricePaise: 6000, rating: 4.3, reviews: 55, image: FOOD_IMAGES.rajma, isVeg: true },
  { id: 'dal-makhani', name: 'Dal Makhani', category: 'North Indian', description: 'Slow-cooked black lentils with rich, silky cream.', pricePaise: 8000, rating: 4.6, reviews: 70, image: FOOD_IMAGES.dal, isVeg: true },
  { id: 'veg-hakka-noodles', name: 'Veg Hakka Noodles', category: 'Chinese', description: 'Stir-fried noodles with crisp, fresh vegetables.', pricePaise: 6000, rating: 4.5, reviews: 110, image: FOOD_IMAGES.noodles, isVeg: true, isSpicy: true },
  { id: 'chilli-paneer', name: 'Chilli Paneer', category: 'Chinese', description: 'Spicy and tangy paneer with peppers and sesame.', pricePaise: 8000, rating: 4.6, reviews: 95, image: FOOD_IMAGES.chilliPaneer, isVeg: true, isSpicy: true },
  { id: 'veg-manchurian', name: 'Veg Manchurian', category: 'Chinese', description: 'Crispy veg balls in a savoury, glossy sauce.', pricePaise: 7000, rating: 4.4, reviews: 82, image: FOOD_IMAGES.manchurian, isVeg: true },
  { id: 'chicken-fried-rice', name: 'Chicken Fried Rice', category: 'Chinese', description: 'Flavourful fried rice with tender chicken and herbs.', pricePaise: 8000, rating: 4.5, reviews: 100, image: FOOD_IMAGES.friedRice, isVeg: false },
];
const CATEGORIES = [
  { label: 'All Items', key: 'all', icon: '▦' }, { label: 'Recommended', key: 'Recommended', icon: '★' },
  { label: 'North Indian', key: 'North Indian', icon: '🍛' }, { label: 'Chinese', key: 'Chinese', icon: '🥡' },
  { label: 'Snacks', key: 'Snacks', icon: '🍟' }, { label: 'Beverages', key: 'Beverages', icon: '🥤' },
  { label: 'Combos', key: 'Combos', icon: '🎁' }, { label: 'Healthy', key: 'Healthy', icon: '🌿' },
  { label: 'Desserts', key: 'Desserts', icon: '🍰' },
];
const REVIEWS = [
  { name: 'Aarav Sharma', initials: 'AS', time: '3 days ago', rating: 5, quote: 'Amazing food and great taste! Paneer Butter Masala is a must try. Always fresh and worth it!' },
  { name: 'Priya Singh', initials: 'PS', time: '1 week ago', rating: 4.5, quote: 'Love the variety of options. The Chinese items are really good and portion sizes are perfect.' },
  { name: 'Rohan Mehta', initials: 'RM', time: '2 weeks ago', rating: 4.5, quote: 'Best cafeteria on campus! Food quality, taste and service are consistently great.' },
];
const THUMBNAILS = [HERO_IMAGE, FOOD_IMAGES.paneer, FOOD_IMAGES.biryani, FOOD_IMAGES.noodles];
const LOCAL_CART_KEY = 'unieats:bite-box-cart';

function getStoredCart(defaultLines: CartLine[]): CartLine[] {
  try {
    const value = window.localStorage.getItem(LOCAL_CART_KEY);
    if (!value) return defaultLines;
    const parsed = JSON.parse(value) as CartLine[];
    return Array.isArray(parsed) ? parsed.filter((line) => line && typeof line.id === 'string' && line.quantity > 0) : defaultLines;
  } catch { return defaultLines; }
}

function CafeSidebar({ open, onClose }: { open: boolean; onClose: () => void }) {
  const links = [
    { label: 'Home', to: '/', icon: Compass, end: true }, { label: 'Cafeterias', to: '/shops', icon: Utensils },
    { label: 'My Orders', to: '/orders', icon: ListOrdered }, { label: 'Favorites', to: '/favorites', icon: Heart },
    { label: 'Wallet & Offers', to: '/notifications', icon: WalletCards }, { label: 'Notifications', to: '/notifications', icon: Bell, badge: 3 },
    { label: 'Profile', to: '/notifications', icon: CircleUserRound },
  ];
  return <aside className={cn('cafe-sidebar', open && 'is-open')} aria-label="Customer navigation"><div className="cafe-sidebar-head"><Link to="/" aria-label="UniEats home" onClick={onClose}><BrandMark /></Link><button type="button" className="cafe-sidebar-close" onClick={onClose} aria-label="Close navigation"><X size={19} /></button></div><nav className="cafe-sidebar-nav">{links.map(({ label, to, icon: Icon, end, badge }) => <NavLink key={label} to={to} end={end} onClick={onClose} className={({ isActive }) => cn('cafe-sidebar-link', isActive && 'is-active')}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{badge && <b>{badge}</b>}</NavLink>)}</nav><div className="cafe-sidebar-divider" /><Link className="cafe-sidebar-link cafe-sidebar-logout" to="/login"><LogOut size={17} /><span>Logout</span></Link></aside>;
}

function CafeHeader({ cartCount, onMenuOpen }: { cartCount: number; onMenuOpen: () => void }) {
  const { user } = useAuth(); const [query, setQuery] = useState(''); const firstName = user?.fullName?.split(' ')[0] ?? 'Vicky';
  return <header className="cafe-header"><button type="button" className="cafe-menu-button" onClick={onMenuOpen} aria-label="Open navigation"><MenuIcon size={20} /></button><form className="cafe-global-search" onSubmit={(event) => event.preventDefault()}><Search size={17} /><input aria-label="Search for food, cafeterias, or cuisines" placeholder="Search for food, cafeterias, or cuisines..." value={query} onChange={(event) => setQuery(event.target.value)} /><button type="submit" aria-label="Search"><Search size={16} /></button></form><div className="cafe-header-actions"><button className="cafe-campus" type="button"><MapPin size={18} /><span><b>Your Campus</b><small>Main Campus</small></span><ChevronDown size={14} /></button><Link to="/cart" className="cafe-header-cart" aria-label={`Cart with ${cartCount} items`}><ShoppingBag size={20} />{cartCount > 0 && <b>{cartCount}</b>}</Link><Link to={user ? '/notifications' : '/login'} className="cafe-user"><span className="cafe-avatar">{user?.profileImageUrl ? <img src={user.profileImageUrl} alt="" /> : firstName.slice(0, 1)}</span><span><b>Hi, {firstName}</b><small>Student</small></span></Link></div></header>;
}

function Hero({ shop, favorite, onFavorite, onShare }: { shop: Shop; favorite: boolean; onFavorite: () => void; onShare: () => void }) {
  return <section className="cafe-hero"><img className="cafe-hero-image" src={HERO_IMAGE} alt="Students enjoying food inside a modern university cafeteria" /><div className="cafe-hero-shade" /><div className="cafe-hero-actions"><button type="button" className={cn('cafe-icon-button', favorite && 'is-favorite')} onClick={onFavorite} aria-label={favorite ? 'Remove from favorites' : 'Add to favorites'}><Heart size={19} fill={favorite ? 'currentColor' : 'none'} /></button><button type="button" className="cafe-share-button" onClick={onShare}><Share2 size={16} />Share</button></div><div className="cafe-hero-copy"><div className="cafe-status-line"><span className="cafe-status"><span />{shop.isOpen ? 'Open Now' : 'Closed'}</span><span>{shop.closingTime ? `Closes at ${shop.closingTime.slice(0, 5)}` : 'Campus hours'}</span></div><h1>{shop.name || 'Bite Box'}</h1><div className="cafe-hero-meta"><span className="cafe-rating"><Star size={16} fill="currentColor" />{shop.rating.toFixed(1)} ({shop.totalReviews} reviews)</span>{(shop.cuisineCategories?.length ? shop.cuisineCategories : ['North Indian', 'Chinese', 'Snacks']).map((category, index) => <span key={category}>{index > 0 && <i>·</i>} {category}</span>)}</div><p>{shop.description || 'Good Food. Good Vibes. Always.'}</p><div className="cafe-hero-info"><span><Clock3 size={16} /><b>{shop.openingTime && shop.closingTime ? `${shop.openingTime.slice(0, 5)} – ${shop.closingTime.slice(0, 5)}` : 'Campus hours'}</b></span><span><MapPin size={16} /><b>{shop.distanceKm ? `${shop.distanceKm.toFixed(1)} km away` : 'On campus'}</b><small>{shop.location || 'Main Campus, Block A'}</small></span><span><CircleUserRound size={16} /><b>Popular among students</b></span></div></div><div className="cafe-photo-strip" aria-label="Cafeteria photos">{THUMBNAILS.map((image, index) => <img key={image} src={image} alt={index === 0 ? 'Cafeteria interior' : `Bite Box food photo ${index}`} />)}<button type="button" onClick={onShare}><span>+12</span>Photos</button></div></section>;
}

function CafeTabs({ activeTab, onChange }: { activeTab: TabId; onChange: (tab: TabId) => void }) { const tabs: Array<[TabId, string]> = [['menu', 'Menu'], ['about', 'About'], ['reviews', 'Reviews (320)'], ['photos', 'Photos'], ['location', 'Location']]; return <nav className="cafe-tabs" aria-label="Cafeteria details"><div>{tabs.map(([id, label]) => <button type="button" key={id} className={activeTab === id ? 'is-active' : ''} onClick={() => onChange(id)}>{label}</button>)}</div></nav>; }

function MenuCategories({ selected, onSelect }: { selected: string; onSelect: (category: string) => void }) { return <aside className="cafe-category-column"><div className="cafe-category-card"><div className="cafe-card-kicker">Explore the menu</div><h2>Menu Categories</h2><nav aria-label="Menu categories">{CATEGORIES.map((category) => <button type="button" key={category.key} className={selected === category.key ? 'is-active' : ''} onClick={() => onSelect(category.key)}><span className="cafe-category-icon">{category.icon}</span><b>{category.label}</b>{selected === category.key && <ChevronRight size={14} />}</button>)}</nav></div><div className="cafe-love-card"><div><span className="cafe-card-kicker">Campus favourite</span><h3>Students Love Bite Box!</h3><p>Fresh ingredients, great taste, and unbeatable vibes.</p></div><span className="cafe-scribble">made with<br />♥ on campus</span><img src={FOOD_IMAGES.biryani} alt="Fresh Bite Box bowl" /></div></aside>; }

function MenuToolbar({ search, onSearch, dietFilter, onDietChange, bestOnly, onBestChange }: { search: string; onSearch: (value: string) => void; dietFilter: DietFilter; onDietChange: (filter: DietFilter) => void; bestOnly: boolean; onBestChange: (value: boolean) => void }) { return <div className="cafe-menu-toolbar"><label className="cafe-menu-search"><Search size={16} /><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search menu items..." aria-label="Search menu items" /></label><div className="cafe-filter-chips"><button type="button" className={dietFilter === 'veg' ? 'is-active veg' : 'veg'} onClick={() => onDietChange(dietFilter === 'veg' ? 'all' : 'veg')}><Leaf size={15} />Veg</button><button type="button" className={dietFilter === 'nonveg' ? 'is-active nonveg' : 'nonveg'} onClick={() => onDietChange(dietFilter === 'nonveg' ? 'all' : 'nonveg')}><span>🍗</span>Non-Veg</button><button type="button" className={bestOnly ? 'is-active best' : 'best'} onClick={() => onBestChange(!bestOnly)}><Star size={14} fill="currentColor" />Bestseller</button></div></div>; }

function FoodCard({ item, onAdd }: { item: ShowcaseItem; onAdd: () => void }) { return <article className="cafe-food-card"><div className="cafe-food-image"><img src={item.image} alt={item.name} loading="lazy" />{item.badge && <span className={cn('cafe-food-badge', item.badge === 'Popular' && 'popular')}>{item.badge === 'Bestseller' ? '★ ' : '● '}{item.badge}</span>}<span className={cn('cafe-diet-dot', item.isVeg ? 'veg' : 'nonveg')} aria-label={item.isVeg ? 'Vegetarian' : 'Non-vegetarian'} /></div><div className="cafe-food-copy"><h3>{item.name}</h3><div className="cafe-food-rating"><Star size={13} fill="currentColor" /><b>{item.rating.toFixed(1)}</b><span>({item.reviews})</span></div><p>{item.description}</p><div className="cafe-food-footer"><strong>{formatRupees(item.pricePaise)}</strong><button type="button" onClick={onAdd} aria-label={`Add ${item.name} to cart`}><Plus size={14} />Add</button></div></div></article>; }

function MenuSection({ title, items, onAdd }: { title: string; items: ShowcaseItem[]; onAdd: (item: ShowcaseItem) => void }) { if (!items.length) return null; return <section className="cafe-menu-section"><div className="cafe-section-title"><h2>{title}</h2><button type="button">View All <ArrowRight size={14} /></button></div><div className="cafe-food-grid">{items.map((item) => <FoodCard key={item.id} item={item} onAdd={() => onAdd(item)} />)}</div></section>; }

function QuantityControl({ quantity, onDecrease, onIncrease, label }: { quantity: number; onDecrease: () => void; onIncrease: () => void; label: string }) { return <div className="cafe-quantity" aria-label={`${label} quantity`}><button type="button" onClick={onDecrease} aria-label={`Decrease ${label}`}><Minus size={13} /></button><span>{quantity}</span><button type="button" onClick={onIncrease} aria-label={`Increase ${label}`}><Plus size={13} /></button></div>; }

function OrderInfo() { const details: Array<[ReactNode, string, string]> = [[<ShoppingBag size={16} />, 'Minimum Order', 'No minimum order amount'], [<Navigation size={16} />, 'Pickup Only', 'Available at cafeteria'], [<WalletCards size={16} />, 'Payment Method', 'Cash on Pickup'], [<Clock3 size={16} />, 'Estimated Pickup Time', '15 – 20 minutes']]; return <section className="cafe-order-info">{details.map(([icon, title, copy]) => <div key={title}><span>{icon}</span><p><b>{title}</b><small>{copy}</small></p></div>)}</section>; }
function OfferCard() { return <section className="cafe-offer-card"><div><span className="cafe-card-kicker">Limited time offer</span><h2>Get 10% Off</h2><p>On orders above ₹200</p><b>Use Code: BITE10</b></div><img src={FOOD_IMAGES.noodles} alt="Bowl of noodles" /></section>; }
function CartSidebar({ lines, onDecrease, onIncrease, onRemove, onClear }: { lines: CartLine[]; onDecrease: (line: CartLine) => void; onIncrease: (line: CartLine) => void; onRemove: (line: CartLine) => void; onClear: () => void }) { const total = lines.reduce((sum, line) => sum + line.pricePaise * line.quantity, 0); return <div className="cafe-order-stack"><section className="cafe-order-card"><div className="cafe-order-heading"><div><span className="cafe-card-kicker">Pickup order</span><h2>Your Order</h2></div><button type="button" onClick={onClear} disabled={!lines.length}>Clear All</button></div>{lines.length ? <div className="cafe-order-lines">{lines.map((line) => <div className="cafe-order-line" key={line.id}><img src={line.image} alt="" /><div className="cafe-order-line-copy"><h3>{line.name}</h3><div><QuantityControl quantity={line.quantity} onDecrease={() => onDecrease(line)} onIncrease={() => onIncrease(line)} label={line.name} /><button type="button" className="cafe-remove" onClick={() => onRemove(line)} aria-label={`Remove ${line.name}`}>×</button></div></div><strong>{formatRupees(line.pricePaise * line.quantity)}</strong></div>)}</div> : <div className="cafe-empty-order"><ShoppingBag size={22} /><p>Your order is waiting for something delicious.</p></div>}<div className="cafe-order-total"><span>Total</span><strong>{formatRupees(total)}</strong></div><Link className={cn('cafe-view-cart', !lines.length && 'is-disabled')} to="/cart" aria-disabled={!lines.length} onClick={(event) => !lines.length && event.preventDefault()}>View Cart <ArrowRight size={16} /></Link></section><OrderInfo /><OfferCard /></div>; }

function AboutPanel({ shop }: { shop: Shop }) { return <div className="cafe-detail-panel"><div><span className="cafe-card-kicker">About Bite Box</span><h2>Good food, good vibes, always.</h2><p>{shop.description || 'A student-first kitchen serving comforting North Indian classics, quick Chinese favourites, and campus coffee for every kind of day.'}</p></div><div className="cafe-about-facts"><span><Coffee size={18} /><b>Freshly prepared</b><small>Made to order</small></span><span><Clock3 size={18} /><b>Quick pickup</b><small>15–20 minutes</small></span><span><TicketPercent size={18} /><b>Student friendly</b><small>Great value daily</small></span></div></div>; }
function ReviewsPanel() { return <section className="cafe-reviews-panel"><div className="cafe-section-title"><div><span className="cafe-card-kicker"><span>Ratings & reviews</span><span> · 320 campus reviews</span></span><h2>What Students Say</h2></div><button type="button">Write a review <ArrowRight size={14} /></button></div><div className="cafe-review-grid">{REVIEWS.map((review) => <article className="cafe-review-card" key={review.name}><div className="cafe-review-head"><span className="cafe-review-avatar">{review.initials}</span><div><h3>{review.name}</h3><small>{review.time}</small></div><span className="cafe-review-stars"><Star size={13} fill="currentColor" />{review.rating.toFixed(1)}</span></div><p>“{review.quote}”</p></article>)}</div></section>; }
function PhotosPanel() { return <section className="cafe-photos-panel"><div className="cafe-section-title"><div><span className="cafe-card-kicker">Inside Bite Box</span><h2>Made for campus moments.</h2></div><button type="button">See all photos <ArrowRight size={14} /></button></div><div className="cafe-gallery">{[HERO_IMAGE, FOOD_IMAGES.biryani, FOOD_IMAGES.paneer, FOOD_IMAGES.coffee, FOOD_IMAGES.noodles].map((image, index) => <img key={image} src={image} alt={`Bite Box gallery image ${index + 1}`} />)}</div></section>; }
function LocationPanel({ shop }: { shop: Shop }) { return <section className="cafe-location-panel"><div><span className="cafe-card-kicker">Find us on campus</span><h2>Main Campus, Block A</h2><p>{shop.location || 'Student Center · Ground Floor'} · Open today until 9:00 PM</p><button type="button" className="cafe-location-button"><Navigation size={16} />Get directions</button></div><div className="cafe-map-placeholder"><div><MapPin size={24} /><b>Bite Box</b><small>2 mins from you</small></div></div></section>; }
function PromoBanner() { return <section className="cafe-promo-banner"><div><span className="cafe-card-kicker">Special offer</span><h2>Good Food Brings Us Together.</h2><p>Get 10% off on your next order from Bite Box!</p><Link to="/shops/the-courtyard-cafe" className="cafe-promo-button">Order Now <ArrowRight size={15} /></Link></div><div className="cafe-promo-art"><img src={FOOD_IMAGES.paneer} alt="A colourful bowl of paneer and vegetables" /><span>Same<br />Campus<br />More Flavor <b>♡</b></span></div></section>; }
function PageState({ children }: { children: ReactNode }) { return <div className="cafe-page-state">{children}</div>; }

export function ShopPage() {
  const { slug = '' } = useParams(); const { user } = useAuth(); const shop = useShop(slug); const cart = useCart(Boolean(user)); const add = useAddCartItem(); const client = useQueryClient(); const update = useMutation({ mutationFn: ({ id, quantity }: { id: string; quantity: number }) => updateCartItem(id, quantity), onSuccess: (nextCart) => client.setQueryData(['cart'], nextCart) }); const remove = useMutation({ mutationFn: (id: string) => removeCartItem(id), onSuccess: (nextCart) => client.setQueryData(['cart'], nextCart) }); const clear = useMutation({ mutationFn: clearCart, onSuccess: (nextCart) => client.setQueryData(['cart'], nextCart) });
  const isBiteBox = slug === 'the-courtyard-cafe' || shop.data?.shop.name === 'The Courtyard Cafe';
  const initialLines: CartLine[] = isBiteBox ? [{ id: 'paneer-butter-masala', name: 'Paneer Butter Masala', pricePaise: 8000, image: FOOD_IMAGES.paneer, quantity: 1 }, { id: 'cold-coffee', name: 'Cold Coffee', pricePaise: 5000, image: FOOD_IMAGES.coffee, quantity: 1 }] : [];
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false); const [activeTab, setActiveTab] = useState<TabId>('menu'); const [selectedCategory, setSelectedCategory] = useState('all'); const [search, setSearch] = useState(''); const [dietFilter, setDietFilter] = useState<DietFilter>('all'); const [bestOnly, setBestOnly] = useState(false); const [favorite, setFavorite] = useState(false); const [notice, setNotice] = useState(''); const [lines, setLines] = useState<CartLine[]>(() => getStoredCart(initialLines));
  useEffect(() => { try { window.localStorage.setItem(LOCAL_CART_KEY, JSON.stringify(lines)); } catch { /* optional storage */ } }, [lines]);
  const menu = useMemo(() => { const remote = shop.data?.menu ?? []; const aliases: Record<string, string> = { 'Paneer Butter Masala': 'Masala Paneer Wrap', 'Cold Coffee': 'Cold Brew Latte' }; return SHOWCASE_MENU.map((item) => { const match = remote.find((remoteItem: MenuItem) => remoteItem.name === aliases[item.name]); return { ...item, apiItemId: match?.id, image: match?.imageUrl ?? item.image }; }); }, [shop.data?.menu]);
  const filteredMenu = useMemo(() => menu.filter((item) => { const categoryMatch = selectedCategory === 'all' || item.category === selectedCategory || (selectedCategory === 'Recommended' && item.badge); const searchMatch = `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(search.trim().toLowerCase()); const dietMatch = dietFilter === 'all' || (dietFilter === 'veg' ? item.isVeg : !item.isVeg); return categoryMatch && searchMatch && dietMatch && (!bestOnly || item.badge === 'Bestseller'); }), [bestOnly, dietFilter, menu, search, selectedCategory]);
  const sections = useMemo(() => { const order = selectedCategory === 'all' ? ['Recommended', 'North Indian', 'Chinese'] : [selectedCategory]; return order.map((title) => ({ title, items: filteredMenu.filter((item) => item.category === title) })).filter((section) => section.items.length); }, [filteredMenu, selectedCategory]);
  const totalItems = lines.reduce((sum, line) => sum + line.quantity, 0); const totalPrice = lines.reduce((sum, line) => sum + line.pricePaise * line.quantity, 0);
  if (shop.isLoading) return <PageState><LoadingSkeleton className="h-[30rem]" /><div className="mt-6 grid gap-5 md:grid-cols-3"><LoadingSkeleton className="h-80" /><LoadingSkeleton className="h-80" /><LoadingSkeleton className="h-80" /></div></PageState>;
  if (shop.isError || !shop.data) return <PageState><ErrorState message="We couldn't load this cafeteria. Please try again." /></PageState>;
  const details = shop.data.shop;
  const updateLine = (line: CartLine, quantity: number) => { if (quantity < 1) setLines((current) => current.filter((currentLine) => currentLine.id !== line.id)); else setLines((current) => current.map((currentLine) => currentLine.id === line.id ? { ...currentLine, quantity } : currentLine)); const serverItem = cart.data?.items.find((item) => item.itemName === line.name); if (serverItem && quantity > 0) update.mutate({ id: serverItem.id, quantity }); if (serverItem && quantity < 1) remove.mutate(serverItem.id); };
  const addItem = async (item: ShowcaseItem) => { setLines((current) => { const existing = current.find((line) => line.id === item.id); return existing ? current.map((line) => line.id === item.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { id: item.id, name: item.name, pricePaise: item.pricePaise, image: item.image, quantity: 1, apiItemId: item.apiItemId }]; }); setNotice(`${item.name} added to your cart.`); if (user && item.apiItemId) { try { await add.mutateAsync({ menuItemId: item.apiItemId, quantity: 1 }); } catch (error) { setNotice(getApiError(error, `${item.name} was saved locally, but we could not sync your cart.`)); } } };
  const clearAll = () => { setLines([]); if (cart.data?.items.length) clear.mutate(); }; const onShare = async () => { try { await navigator.clipboard?.writeText(window.location.href); setNotice('Bite Box link copied to your clipboard.'); } catch { setNotice('Share link ready — copy the page URL to share it.'); } }; const changeTab = (tab: TabId) => { setActiveTab(tab); if (tab !== 'menu') setNotice(`${tab[0].toUpperCase()}${tab.slice(1)} view selected.`); };
  return <div className="cafe-app"><CafeSidebar open={mobileSidebarOpen} onClose={() => setMobileSidebarOpen(false)} /><div className="cafe-main"><CafeHeader cartCount={totalItems} onMenuOpen={() => setMobileSidebarOpen(true)} /><main className="cafe-content"><Hero shop={details} favorite={favorite} onFavorite={() => { setFavorite((value) => !value); setNotice(favorite ? 'Removed from favorites.' : 'Bite Box saved to favorites.'); }} onShare={() => void onShare()} /><CafeTabs activeTab={activeTab} onChange={changeTab} />{notice && <div className="cafe-notice" role="status"><Check size={16} />{notice}<button type="button" onClick={() => setNotice('')} aria-label="Dismiss notification"><X size={14} /></button></div>}
        {activeTab === 'menu' && <div className="cafe-menu-layout"><MenuCategories selected={selectedCategory} onSelect={setSelectedCategory} /><section className="cafe-menu-column"><div className="cafe-section-title"><div><span className="cafe-card-kicker">Fresh from the kitchen</span><h2>What sounds good?</h2></div></div><MenuToolbar search={search} onSearch={setSearch} dietFilter={dietFilter} onDietChange={setDietFilter} bestOnly={bestOnly} onBestChange={setBestOnly} />{sections.map((section) => <MenuSection key={section.title} title={section.title} items={section.items} onAdd={(item) => void addItem(item)} />)}{!sections.length && <div className="cafe-no-results"><Search size={24} /><h2>No bites match that search.</h2><p>Try a different category or clear one of your filters.</p><button type="button" onClick={() => { setSearch(''); setSelectedCategory('all'); setDietFilter('all'); setBestOnly(false); }}>Clear filters</button></div>}</section><aside className="cafe-order-column"><CartSidebar lines={lines} onDecrease={(line) => updateLine(line, line.quantity - 1)} onIncrease={(line) => updateLine(line, line.quantity + 1)} onRemove={(line) => updateLine(line, 0)} onClear={clearAll} /></aside></div>}
        {activeTab === 'about' && <AboutPanel shop={details} />}{activeTab === 'reviews' && <ReviewsPanel />}{activeTab === 'photos' && <PhotosPanel />}{activeTab === 'location' && <LocationPanel shop={details} />}
        <section className="cafe-reviews-section"><div className="cafe-section-title"><div><span className="cafe-card-kicker"><span>Ratings & reviews</span><span> · From the campus community</span></span><h2>What Students Say</h2></div><button type="button" onClick={() => changeTab('reviews')}>View All Reviews <ArrowRight size={14} /></button></div><div className="cafe-review-grid">{REVIEWS.map((review) => <article className="cafe-review-card" key={`lower-${review.name}`}><div className="cafe-review-head"><span className="cafe-review-avatar">{review.initials}</span><div><h3>{review.name}</h3><small>{review.time}</small></div><span className="cafe-review-stars"><Star size={13} fill="currentColor" />{review.rating.toFixed(1)}</span></div><p>“{review.quote}”</p></article>)}</div></section><PromoBanner /><div className="cafe-mobile-order"><ShoppingBag size={18} /><span>{totalItems} {totalItems === 1 ? 'item' : 'items'} · <b>{formatRupees(totalPrice)}</b></span><Link to="/cart">View Cart <ArrowRight size={14} /></Link></div>
      </main><Footer /></div><nav className="cafe-mobile-nav" aria-label="Mobile navigation"><NavLink to="/" end><Compass size={18} /><span>Home</span></NavLink><NavLink to="/shops"><Utensils size={18} /><span>Explore</span></NavLink><NavLink to="/orders"><ListOrdered size={18} /><span>Orders</span></NavLink><NavLink to="/notifications"><CircleUserRound size={18} /><span>Profile</span></NavLink></nav></div>;
}
